### ISSUE TITLE
Unable to overwrite current installation

### ISSUE THREAD

**Issue by UltraHKR** [nutdotnet/WinNUT-Client#26]
Hi, I'm trying to update between v2.2.8255.34401 to v2.2.8286-installer

Windows installer shows with the following error: 
![image](https://user-images.githubusercontent.com/49404533/191816984-f2cb8f1c-0429-4e25-8ce8-5f832607a04b.png)

It should properly overwrite, existing install.

I had to uninstall old version, to upgrade

**Comment by gbakeman** [comment]
Thank you for the notification, it looks like I broken the versioning on the Setup package. I've attempted to fix this in the [latest release here](https://github.com/nutdotnet/WinNUT-Client/releases/tag/v2.2.8303).

I think everyone will need to uninstall the old (broken) version for future upgrades to work. Otherwise this will just create a second installation entry for WinNUT in your installed programs list.

Please let me know in this ticket if future releases still have this issue.
